module.exports = {
  endpoint: {
    url: 'api.openweathermap.org/data',
    protocol: 'https',
    version: '2.5',
  },
  default: {
    apikey: 'c15053e7a024be38ee66e8c9cc995324',
    lang: 'en',
    units: 'standart',
    mode: 'json',
  },
  units: {
    metric: 'metric',
    standart: 'standart',
    imperial: 'imperial',
  },
  mode: {
    xml: 'xml',
    json: 'json',
    html: 'html',
  },
  lang: {
    ar: 'Arabic',
    bg: 'Bulgarian',
    ca: 'Catalan',
    cz: 'Czech',
    de: 'German',
    el: 'Greek',
    en: 'English',
    fa: 'Persian (Farsi)',
    fi: 'Finnish',
    fr: 'French',
    gl: 'Galician',
    hr: 'Croatian',
    hu: 'Hungarian',
    it: 'Italian',
    ja: 'Japanese',
    kr: 'Korean',
    la: 'Latvian',
    lt: 'Lithuanian',
    mk: 'Macedonian',
    nl: 'Dutch',
    pl: 'Polish',
    pt: 'Portuguese',
    ro: 'Romanian',
    ru: 'Russian',
    se: 'Swedish',
    sk: 'Slovak',
    sl: 'Slovenian',
    es: 'Spanish',
    tr: 'Turkish',
    ua: 'Ukrainian',
    vi: 'Vietnamese',
    zh_cn: 'Chinese Simplified',
    zh_tw: 'Chinese Traditional',
  },
}
